### ISSUE TITLE
ENH: Support docutils 0.17.1

### ISSUE THREAD

**Issue by mmcky** [executablebooks/sphinx-book-theme#392]
### Description / Summary

The `docutils==0.17+` package makes changes to `css`

From @chrisjsewell

It now uses a bunch of semantic HTML tags: `<main>`, `<section>`, `<header>`, `<footer>`, `<aside>`, `<figure>`, and `<figcaption>`, instead of e.g. `<div class="section">` (see https://github.com/sphinx-doc/sphinx/issues/9001)

It will break lots of current CSS, like: https://github.com/executablebooks/sphinx-book-theme/blob/43506962d4f90e6fc74d209d72503929900d84e7/src/scss/_page.scss#L66

### Value / benefit

Enable the use of `docutils==0.17` as the stack get's upgraded

### Implementation details

The question is should we support only `0.17` or previous version of `docutils` as well?

- [x] `docutils>=0.17.1`
- [x] `docutils==0.16`

Aim is to support `docutils>=0.15`

**note** that we probably want to skip `0.17.0` because it has a nasty bug in it, so we should begin with `0.17.1`

### Tasks to complete

- [ ] Allow 0.17 series docutils in our dependencies
- [ ] Ensure that our documentation builds use v0.17
- [ ] Take a careful look at the CSS to make sure that nothing has broken (see https://github.com/sphinx-doc/sphinx/issues/9001 for inspiration of what to look for)
- [ ] For anything that is broken, add additional CSS rules to accommodate both 0.17 AND below
- [ ] Decide if those rules are too complex to be unmaintainable and resolve if needed
- [ ] Ensure that RTD builds use v0.17

**Comment by pradyunsg** [comment]
Is there any specific reason to support `==0.17` of docutils, when there's a newer bugfix (0.17.1) that fixes certain backwards incompatible bugs?

Sphinx 4 had a pin due to those bugs, but that was removed once there was a new release with those bugs fixed (see discussion in https://github.com/sphinx-doc/sphinx/issues/9088).

**Comment by chrisjsewell** [comment]
> Is there any specific reason to support ==0.17 of docutils, when there's a newer bugfix (0.17.1) that fixes certain backwards incompatible bugs?

By `==0.17` he just all versions of 0.17, i.e. going from 0.16 to 0.17 there is a step change in the HTAML output and thus CSS required, so do you write your CSS to handle both output cases (more complexity), or do you drop support for <0.17 (less compatible)
Have you handled this yet in Furo?

**Comment by choldgraf** [comment]
good point though @pradyunsg - I updated the top comment to note that we wanna start w/ 17.1

**Comment by mmcky** [comment]
thanks everyone -- thanks @pradyunsg will start from `0.17.1` 👍

**Comment by mmcky** [comment]
Do we need to support `docutils=0.16,<0.17` moving forward?

**Comment by chrisjsewell** [comment]
I checked and yeh Furo has duel statments e.g. `figure, .figure`, so I assume it is possible, and that we would want to

**Comment by choldgraf** [comment]
I've updated the top comment with what I think are the next steps here 👍
