### ISSUE TITLE
Use kitchen sink from `sphinx-themes.org` for our reference docs

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/sphinx-book-theme#402]
### Description / Summary

Our reference docs are a little bit cluttered, have some duplicated information, and aren't particularly standardized.

I've been chatting with @pradyunsg about lightly modifying the kitchen sink from sphinx-themes.org so that other themes may re-use them (e.g. so that they don't have errors in them, don't have site-specific links, etc).

Once any needed changes are made there, we can give a shot at incorporating them manually into our docs and removing the duplicated information.

### Value / benefit

The main benefit here is that we can standardize on the sphinx-themes kitchen sink, so:

- the patterns we follow here may be more familiar to others
- as kitchen-sink improves this reference material, we'll also inherit those improvements
- the material is generally well-organized already

### Implementation details

I think the easiest thing to do would be to manually list the "raw paths" to the GitHub objects for these files, and download them with `requests` as part of our docs build (maybe only downloading them if the files are not present locally, so we can "flush the cache" by deleting them to update the files.

Here are the files we could pull in:

- https://github.com/sphinx-themes/sphinx-themes.org/raw/master/sample-docs/kitchen-sink/api.rst
- https://github.com/sphinx-themes/sphinx-themes.org/raw/master/sample-docs/kitchen-sink/lists-and-tables.rst
- https://github.com/sphinx-themes/sphinx-themes.org/raw/master/sample-docs/kitchen-sink/paragraph-markup.rst

We'll also need to make sure there aren't any "known errors" in these files, since our builds fail if there are warnings.

### Tasks to complete

- [ ] Confirm there isn't any content in the sphinx-themes kitchen sink that will mess with our builds
- [ ] Try downloading them into our docs semi-automatically
- [ ] If it's not too many lines of code / complexity, then replace pre-existing reference material w/ this kitchen sink (for duplicated information, we should keep the theme-specific reference pages)
