### ISSUE TITLE
Remove dependence on jquery

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/sphinx-book-theme#580]
### Context

Sphinx 6.0 is going to remove the jquery dependency by default. We use jquery a little bit in this theme, though likely not in a way that strictly requires jquery.

[Here's a GitHub CS search for the `$(` symbol](https://cs.github.com/executablebooks/sphinx-book-theme?q=%24%28)

Note that our parent theme removed JQuery as a dependency here:

- https://github.com/pydata/pydata-sphinx-theme/pull/1029

### Proposal

We should remove all of our code that depends on JQuery, and only manually add the JQuery dependency if we really need it.

### Tasks and updates

- [ ] Remove instances of `$(` in the theme as well as JQuery notes anywhere
- [ ] Remove `tooltip` functionality and popper.js
- [ ] Remove the styling of `div.tooltip` since we no longer use Bootstrap for this
- [ ] Double-check functionality is the same
