### ISSUE TITLE
Enhancement to docs - how to customize left navigation bar with titles using toctree

### ISSUE THREAD

**Issue by lwasser** [executablebooks/sphinx-book-theme#629]
### Context

Related to [this discussion](https://github.com/orgs/executablebooks/discussions/854) i'm interested in adding some content on how to customize the left nav bar in sphinx book theme using myST ...

I'm actually tho not sure where to place it in the book so i'm open to options.
This is all about customizing the nav but it's more config level customization vs content in the nav. but it could go on that page. 

### Proposal

Essentially i'd like to submit a PR that shows a user how to use the syntax below to create a clean navigation panel with shorter titles  using syntax like what is below

````
```{toctree}
:hidden:
:caption: Documentation

your title here documentation/intro
your title here documentation/readme-files 
```
````

### Tasks and updates

- [ ] Decide where this documentation should go. it is almost a little vignette or how to as it's part myST and related to sphinx book.
- [ ] Let me submit a PR with text that everyone here can review until we are all happy!
- [ ] Let happy users easily create nav across their books using the magical `:hidden:` element and clean nav titles 🎉 

If this is of interest, id just like some guidance on where you'd like to see this in the docs and then i'll work on it and submit a PR! cheers! ya'll are doing some amazing work here!
