### ISSUE TITLE
Switch to `ruff`

### ISSUE THREAD

**Issue by adam-grant-hendry** [executablebooks/sphinx-book-theme#769]
### Context

`flake8` takes  a long time to run (i.e. `pre-commit`). It would be nicer to use [`ruff`](https://astral.sh/ruff).

### Proposal

1. Remove `flake8` as a dependency, including the `.flake8` file.
2. Add `ruff` rules to `pyproject.toml` file
3. Modify `.pre-commit-config.yaml` to use `ruff`

### Tasks and updates

- [ ] Remove `flake8` as a dependency, including the `.flake8` file.
- [ ] Add `ruff` rules to `pyproject.toml` file
- [ ] Modify `.pre-commit-config.yaml` to use `ruff`

**Comment by choldgraf** [comment]
Makes sense to me - I think that @agoose77 recently updated to ruff on some other projects in EB as well.

**Comment by adam-grant-hendry** [comment]
@choldgraf @agoose77 flake8 takes the longest linting time, not black. Can we reopen this until we switch from flake8 to ruff?

**Comment by agoose77** [comment]
We should do both - let me check, I thought I'd removed flake8 but it's been a very long week...
